[project]
name = "rl-stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.2",
    "matplotlib>=3.9.0",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.3",
    "swig>=4.4.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "pyyaml>=6.0",
]
