# Training and System Configuration
USE_MIXED_PRECISION: True
USE_TORCH_COMPILE: False

# Model Configuration
model_name: "TinyCNN"

# PPO Hyperparameters
LEARNING_RATE: 0.0001
GAMMA: 0.99
GAE_LAMBDA: 0.95
VALUE_COEFF: 0.5
ENTROPY_COEFF: 0.005
CLIP_EPSILON: 0.2
PPO_EPOCHS: 4
BATCH_SIZE: 512
NUM_ROUNDS: 10000
